name: Deploy Vite Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Vite Application
        run: npm run build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build --tag samdeepsharma/inotebook-cloud \
            --build-arg SERVER_BASE_URL="${{ secrets.SERVER_BASE_URL }}" \
            .

      - name: Publish Image to Docker Hub
        run: docker push samdeepsharma/inotebook-cloud:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull samdeepsharma/inotebook-cloud:latest

      - name: Stop and Remove Old Container
        run: |
          docker stop react-app-container || true
          docker rm react-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 5173:5173 \
            --name react-app-container \
            samdeepsharma/inotebook-cloud:latest
